spring:
  application:
    name: rate-printer

rate-printer:
  from-currency: USD
  to-currency: RUB
  poll-interval-ms: 5000

zookeeper:
  connect-string: localhost:2181
  service-path: /services
  session-timeout-ms: 30000
  connection-timeout-ms: 15000