spring:
  application:
    name: currency-rate-provider

grpc:
  server:
    port: 9090

currency:
  base-rates:
    USDRUB: 92.50
    EURRUB: 100.30

zookeeper:
  connect-string: localhost:2181
  service-path: /services
  session-timeout-ms: 30000
  connection-timeout-ms: 15000